spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v9?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: WYF3qOoQUvQXrJ0mxJKOv+xm247TxvliKQitbpSPoIPhpibZty/SRE/PCo4ZH94vrmdupuGymDooLcDv/ki7ow==
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10
      filter:
        config:
          enabled: true
      connection-properties: config.decrypt=true;config.decrypt.key=${public-key}

public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJHmH6j61MizxFXu9/8U7uBOVtipwlALTEZRn6hOqaT0fYsIydDy3BSOvmpWLiyBmq6eCso8Z8YaHZTozVnR8bMCAwEAAQ==

dubbo:
  application:
    name: product-service
  registry:
    protocol: zookeeper
    address: 192.168.244.129:2181
  protocol:
    port: 28810
